package com.example.demo.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Sun Jun 17 13:23:25 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.l1
     *
     * @mbg.generated Sun Jun 17 13:23:25 CST 2018
     */
    private String l1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.l2
     *
     * @mbg.generated Sun Jun 17 13:23:25 CST 2018
     */
    private String l2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Sun Jun 17 13:23:25 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Sun Jun 17 13:23:25 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.l1
     *
     * @return the value of user.l1
     *
     * @mbg.generated Sun Jun 17 13:23:25 CST 2018
     */
    public String getL1() {
        return l1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.l1
     *
     * @param l1 the value for user.l1
     *
     * @mbg.generated Sun Jun 17 13:23:25 CST 2018
     */
    public void setL1(String l1) {
        this.l1 = l1 == null ? null : l1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.l2
     *
     * @return the value of user.l2
     *
     * @mbg.generated Sun Jun 17 13:23:25 CST 2018
     */
    public String getL2() {
        return l2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.l2
     *
     * @param l2 the value for user.l2
     *
     * @mbg.generated Sun Jun 17 13:23:25 CST 2018
     */
    public void setL2(String l2) {
        this.l2 = l2 == null ? null : l2.trim();
    }
}