server:
    port: 9097

spring:
    datasource:
        url: jdbc:oracle:thin:@192.168.1.1:1521:ee
        username: system
        password: pass

    data.mongodb:
        uri: mongodb://root:pass@1.2.1.1:27017/admin

mybatis:
    mapper-locations: classpath:mappers/*/*.xml