package com.example.demo.dao.xxt;

import com.example.demo.model.xxt.Encounter;
import com.example.demo.model.xxt.EncounterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EncounterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    long countByExample(EncounterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    int deleteByExample(EncounterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    int deleteByPrimaryKey(Long encounterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    int insert(Encounter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    int insertSelective(Encounter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    List<Encounter> selectByExample(EncounterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    Encounter selectByPrimaryKey(Long encounterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") Encounter record, @Param("example") EncounterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    int updateByExample(@Param("record") Encounter record, @Param("example") EncounterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    int updateByPrimaryKeySelective(Encounter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    int updateByPrimaryKey(Encounter record);
}