package com.example.demo.model.xxt;

import java.util.Date;

public class Encounter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANGCHAO_XT.ENCOUNTER.ENCOUNTER_ID
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    private Long encounterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANGCHAO_XT.ENCOUNTER.PATIENT_ID
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    private Long patientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANGCHAO_XT.ENCOUNTER.HOSPITAL_ID
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    private Long hospitalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANGCHAO_XT.ENCOUNTER.ENC_AGE
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    private String encAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANGCHAO_XT.ENCOUNTER.ENC_TYPE
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    private String encType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANGCHAO_XT.ENCOUNTER.ENC_NO_TYPE
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    private String encNoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANGCHAO_XT.ENCOUNTER.ENC_NO
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    private String encNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANGCHAO_XT.ENCOUNTER.START_TIME
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANGCHAO_XT.ENCOUNTER.END_TIME
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANGCHAO_XT.ENCOUNTER.LOS
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    private String los;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANGCHAO_XT.ENCOUNTER.ADMIT_DEPT_NAME
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    private String admitDeptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANGCHAO_XT.ENCOUNTER.DIS_DEPT_NAME
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    private String disDeptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANGCHAO_XT.ENCOUNTER.DIS_TYPE
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    private String disType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LANGCHAO_XT.ENCOUNTER.PARTICIPANT_ID
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    private Long participantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANGCHAO_XT.ENCOUNTER.ENCOUNTER_ID
     *
     * @return the value of LANGCHAO_XT.ENCOUNTER.ENCOUNTER_ID
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public Long getEncounterId() {
        return encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANGCHAO_XT.ENCOUNTER.ENCOUNTER_ID
     *
     * @param encounterId the value for LANGCHAO_XT.ENCOUNTER.ENCOUNTER_ID
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public void setEncounterId(Long encounterId) {
        this.encounterId = encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANGCHAO_XT.ENCOUNTER.PATIENT_ID
     *
     * @return the value of LANGCHAO_XT.ENCOUNTER.PATIENT_ID
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public Long getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANGCHAO_XT.ENCOUNTER.PATIENT_ID
     *
     * @param patientId the value for LANGCHAO_XT.ENCOUNTER.PATIENT_ID
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public void setPatientId(Long patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANGCHAO_XT.ENCOUNTER.HOSPITAL_ID
     *
     * @return the value of LANGCHAO_XT.ENCOUNTER.HOSPITAL_ID
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public Long getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANGCHAO_XT.ENCOUNTER.HOSPITAL_ID
     *
     * @param hospitalId the value for LANGCHAO_XT.ENCOUNTER.HOSPITAL_ID
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public void setHospitalId(Long hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANGCHAO_XT.ENCOUNTER.ENC_AGE
     *
     * @return the value of LANGCHAO_XT.ENCOUNTER.ENC_AGE
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public String getEncAge() {
        return encAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANGCHAO_XT.ENCOUNTER.ENC_AGE
     *
     * @param encAge the value for LANGCHAO_XT.ENCOUNTER.ENC_AGE
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public void setEncAge(String encAge) {
        this.encAge = encAge == null ? null : encAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANGCHAO_XT.ENCOUNTER.ENC_TYPE
     *
     * @return the value of LANGCHAO_XT.ENCOUNTER.ENC_TYPE
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public String getEncType() {
        return encType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANGCHAO_XT.ENCOUNTER.ENC_TYPE
     *
     * @param encType the value for LANGCHAO_XT.ENCOUNTER.ENC_TYPE
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public void setEncType(String encType) {
        this.encType = encType == null ? null : encType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANGCHAO_XT.ENCOUNTER.ENC_NO_TYPE
     *
     * @return the value of LANGCHAO_XT.ENCOUNTER.ENC_NO_TYPE
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public String getEncNoType() {
        return encNoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANGCHAO_XT.ENCOUNTER.ENC_NO_TYPE
     *
     * @param encNoType the value for LANGCHAO_XT.ENCOUNTER.ENC_NO_TYPE
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public void setEncNoType(String encNoType) {
        this.encNoType = encNoType == null ? null : encNoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANGCHAO_XT.ENCOUNTER.ENC_NO
     *
     * @return the value of LANGCHAO_XT.ENCOUNTER.ENC_NO
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public String getEncNo() {
        return encNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANGCHAO_XT.ENCOUNTER.ENC_NO
     *
     * @param encNo the value for LANGCHAO_XT.ENCOUNTER.ENC_NO
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public void setEncNo(String encNo) {
        this.encNo = encNo == null ? null : encNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANGCHAO_XT.ENCOUNTER.START_TIME
     *
     * @return the value of LANGCHAO_XT.ENCOUNTER.START_TIME
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANGCHAO_XT.ENCOUNTER.START_TIME
     *
     * @param startTime the value for LANGCHAO_XT.ENCOUNTER.START_TIME
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANGCHAO_XT.ENCOUNTER.END_TIME
     *
     * @return the value of LANGCHAO_XT.ENCOUNTER.END_TIME
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANGCHAO_XT.ENCOUNTER.END_TIME
     *
     * @param endTime the value for LANGCHAO_XT.ENCOUNTER.END_TIME
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANGCHAO_XT.ENCOUNTER.LOS
     *
     * @return the value of LANGCHAO_XT.ENCOUNTER.LOS
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public String getLos() {
        return los;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANGCHAO_XT.ENCOUNTER.LOS
     *
     * @param los the value for LANGCHAO_XT.ENCOUNTER.LOS
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public void setLos(String los) {
        this.los = los == null ? null : los.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANGCHAO_XT.ENCOUNTER.ADMIT_DEPT_NAME
     *
     * @return the value of LANGCHAO_XT.ENCOUNTER.ADMIT_DEPT_NAME
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public String getAdmitDeptName() {
        return admitDeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANGCHAO_XT.ENCOUNTER.ADMIT_DEPT_NAME
     *
     * @param admitDeptName the value for LANGCHAO_XT.ENCOUNTER.ADMIT_DEPT_NAME
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public void setAdmitDeptName(String admitDeptName) {
        this.admitDeptName = admitDeptName == null ? null : admitDeptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANGCHAO_XT.ENCOUNTER.DIS_DEPT_NAME
     *
     * @return the value of LANGCHAO_XT.ENCOUNTER.DIS_DEPT_NAME
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public String getDisDeptName() {
        return disDeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANGCHAO_XT.ENCOUNTER.DIS_DEPT_NAME
     *
     * @param disDeptName the value for LANGCHAO_XT.ENCOUNTER.DIS_DEPT_NAME
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public void setDisDeptName(String disDeptName) {
        this.disDeptName = disDeptName == null ? null : disDeptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANGCHAO_XT.ENCOUNTER.DIS_TYPE
     *
     * @return the value of LANGCHAO_XT.ENCOUNTER.DIS_TYPE
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public String getDisType() {
        return disType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANGCHAO_XT.ENCOUNTER.DIS_TYPE
     *
     * @param disType the value for LANGCHAO_XT.ENCOUNTER.DIS_TYPE
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public void setDisType(String disType) {
        this.disType = disType == null ? null : disType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LANGCHAO_XT.ENCOUNTER.PARTICIPANT_ID
     *
     * @return the value of LANGCHAO_XT.ENCOUNTER.PARTICIPANT_ID
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public Long getParticipantId() {
        return participantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LANGCHAO_XT.ENCOUNTER.PARTICIPANT_ID
     *
     * @param participantId the value for LANGCHAO_XT.ENCOUNTER.PARTICIPANT_ID
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public void setParticipantId(Long participantId) {
        this.participantId = participantId;
    }
}