package com.example.demo.model.xxt;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EncounterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public EncounterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEncounterIdIsNull() {
            addCriterion("ENCOUNTER_ID is null");
            return (Criteria) this;
        }

        public Criteria andEncounterIdIsNotNull() {
            addCriterion("ENCOUNTER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEncounterIdEqualTo(Long value) {
            addCriterion("ENCOUNTER_ID =", value, "encounterId");
            return (Criteria) this;
        }

        public Criteria andEncounterIdNotEqualTo(Long value) {
            addCriterion("ENCOUNTER_ID <>", value, "encounterId");
            return (Criteria) this;
        }

        public Criteria andEncounterIdGreaterThan(Long value) {
            addCriterion("ENCOUNTER_ID >", value, "encounterId");
            return (Criteria) this;
        }

        public Criteria andEncounterIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ENCOUNTER_ID >=", value, "encounterId");
            return (Criteria) this;
        }

        public Criteria andEncounterIdLessThan(Long value) {
            addCriterion("ENCOUNTER_ID <", value, "encounterId");
            return (Criteria) this;
        }

        public Criteria andEncounterIdLessThanOrEqualTo(Long value) {
            addCriterion("ENCOUNTER_ID <=", value, "encounterId");
            return (Criteria) this;
        }

        public Criteria andEncounterIdIn(List<Long> values) {
            addCriterion("ENCOUNTER_ID in", values, "encounterId");
            return (Criteria) this;
        }

        public Criteria andEncounterIdNotIn(List<Long> values) {
            addCriterion("ENCOUNTER_ID not in", values, "encounterId");
            return (Criteria) this;
        }

        public Criteria andEncounterIdBetween(Long value1, Long value2) {
            addCriterion("ENCOUNTER_ID between", value1, value2, "encounterId");
            return (Criteria) this;
        }

        public Criteria andEncounterIdNotBetween(Long value1, Long value2) {
            addCriterion("ENCOUNTER_ID not between", value1, value2, "encounterId");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNull() {
            addCriterion("PATIENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andPatientIdIsNotNull() {
            addCriterion("PATIENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPatientIdEqualTo(Long value) {
            addCriterion("PATIENT_ID =", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotEqualTo(Long value) {
            addCriterion("PATIENT_ID <>", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThan(Long value) {
            addCriterion("PATIENT_ID >", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PATIENT_ID >=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThan(Long value) {
            addCriterion("PATIENT_ID <", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdLessThanOrEqualTo(Long value) {
            addCriterion("PATIENT_ID <=", value, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdIn(List<Long> values) {
            addCriterion("PATIENT_ID in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotIn(List<Long> values) {
            addCriterion("PATIENT_ID not in", values, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdBetween(Long value1, Long value2) {
            addCriterion("PATIENT_ID between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andPatientIdNotBetween(Long value1, Long value2) {
            addCriterion("PATIENT_ID not between", value1, value2, "patientId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdIsNull() {
            addCriterion("HOSPITAL_ID is null");
            return (Criteria) this;
        }

        public Criteria andHospitalIdIsNotNull() {
            addCriterion("HOSPITAL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalIdEqualTo(Long value) {
            addCriterion("HOSPITAL_ID =", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdNotEqualTo(Long value) {
            addCriterion("HOSPITAL_ID <>", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdGreaterThan(Long value) {
            addCriterion("HOSPITAL_ID >", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdGreaterThanOrEqualTo(Long value) {
            addCriterion("HOSPITAL_ID >=", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdLessThan(Long value) {
            addCriterion("HOSPITAL_ID <", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdLessThanOrEqualTo(Long value) {
            addCriterion("HOSPITAL_ID <=", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdIn(List<Long> values) {
            addCriterion("HOSPITAL_ID in", values, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdNotIn(List<Long> values) {
            addCriterion("HOSPITAL_ID not in", values, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdBetween(Long value1, Long value2) {
            addCriterion("HOSPITAL_ID between", value1, value2, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdNotBetween(Long value1, Long value2) {
            addCriterion("HOSPITAL_ID not between", value1, value2, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andEncAgeIsNull() {
            addCriterion("ENC_AGE is null");
            return (Criteria) this;
        }

        public Criteria andEncAgeIsNotNull() {
            addCriterion("ENC_AGE is not null");
            return (Criteria) this;
        }

        public Criteria andEncAgeEqualTo(String value) {
            addCriterion("ENC_AGE =", value, "encAge");
            return (Criteria) this;
        }

        public Criteria andEncAgeNotEqualTo(String value) {
            addCriterion("ENC_AGE <>", value, "encAge");
            return (Criteria) this;
        }

        public Criteria andEncAgeGreaterThan(String value) {
            addCriterion("ENC_AGE >", value, "encAge");
            return (Criteria) this;
        }

        public Criteria andEncAgeGreaterThanOrEqualTo(String value) {
            addCriterion("ENC_AGE >=", value, "encAge");
            return (Criteria) this;
        }

        public Criteria andEncAgeLessThan(String value) {
            addCriterion("ENC_AGE <", value, "encAge");
            return (Criteria) this;
        }

        public Criteria andEncAgeLessThanOrEqualTo(String value) {
            addCriterion("ENC_AGE <=", value, "encAge");
            return (Criteria) this;
        }

        public Criteria andEncAgeLike(String value) {
            addCriterion("ENC_AGE like", value, "encAge");
            return (Criteria) this;
        }

        public Criteria andEncAgeNotLike(String value) {
            addCriterion("ENC_AGE not like", value, "encAge");
            return (Criteria) this;
        }

        public Criteria andEncAgeIn(List<String> values) {
            addCriterion("ENC_AGE in", values, "encAge");
            return (Criteria) this;
        }

        public Criteria andEncAgeNotIn(List<String> values) {
            addCriterion("ENC_AGE not in", values, "encAge");
            return (Criteria) this;
        }

        public Criteria andEncAgeBetween(String value1, String value2) {
            addCriterion("ENC_AGE between", value1, value2, "encAge");
            return (Criteria) this;
        }

        public Criteria andEncAgeNotBetween(String value1, String value2) {
            addCriterion("ENC_AGE not between", value1, value2, "encAge");
            return (Criteria) this;
        }

        public Criteria andEncTypeIsNull() {
            addCriterion("ENC_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andEncTypeIsNotNull() {
            addCriterion("ENC_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andEncTypeEqualTo(String value) {
            addCriterion("ENC_TYPE =", value, "encType");
            return (Criteria) this;
        }

        public Criteria andEncTypeNotEqualTo(String value) {
            addCriterion("ENC_TYPE <>", value, "encType");
            return (Criteria) this;
        }

        public Criteria andEncTypeGreaterThan(String value) {
            addCriterion("ENC_TYPE >", value, "encType");
            return (Criteria) this;
        }

        public Criteria andEncTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ENC_TYPE >=", value, "encType");
            return (Criteria) this;
        }

        public Criteria andEncTypeLessThan(String value) {
            addCriterion("ENC_TYPE <", value, "encType");
            return (Criteria) this;
        }

        public Criteria andEncTypeLessThanOrEqualTo(String value) {
            addCriterion("ENC_TYPE <=", value, "encType");
            return (Criteria) this;
        }

        public Criteria andEncTypeLike(String value) {
            addCriterion("ENC_TYPE like", value, "encType");
            return (Criteria) this;
        }

        public Criteria andEncTypeNotLike(String value) {
            addCriterion("ENC_TYPE not like", value, "encType");
            return (Criteria) this;
        }

        public Criteria andEncTypeIn(List<String> values) {
            addCriterion("ENC_TYPE in", values, "encType");
            return (Criteria) this;
        }

        public Criteria andEncTypeNotIn(List<String> values) {
            addCriterion("ENC_TYPE not in", values, "encType");
            return (Criteria) this;
        }

        public Criteria andEncTypeBetween(String value1, String value2) {
            addCriterion("ENC_TYPE between", value1, value2, "encType");
            return (Criteria) this;
        }

        public Criteria andEncTypeNotBetween(String value1, String value2) {
            addCriterion("ENC_TYPE not between", value1, value2, "encType");
            return (Criteria) this;
        }

        public Criteria andEncNoTypeIsNull() {
            addCriterion("ENC_NO_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andEncNoTypeIsNotNull() {
            addCriterion("ENC_NO_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andEncNoTypeEqualTo(String value) {
            addCriterion("ENC_NO_TYPE =", value, "encNoType");
            return (Criteria) this;
        }

        public Criteria andEncNoTypeNotEqualTo(String value) {
            addCriterion("ENC_NO_TYPE <>", value, "encNoType");
            return (Criteria) this;
        }

        public Criteria andEncNoTypeGreaterThan(String value) {
            addCriterion("ENC_NO_TYPE >", value, "encNoType");
            return (Criteria) this;
        }

        public Criteria andEncNoTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ENC_NO_TYPE >=", value, "encNoType");
            return (Criteria) this;
        }

        public Criteria andEncNoTypeLessThan(String value) {
            addCriterion("ENC_NO_TYPE <", value, "encNoType");
            return (Criteria) this;
        }

        public Criteria andEncNoTypeLessThanOrEqualTo(String value) {
            addCriterion("ENC_NO_TYPE <=", value, "encNoType");
            return (Criteria) this;
        }

        public Criteria andEncNoTypeLike(String value) {
            addCriterion("ENC_NO_TYPE like", value, "encNoType");
            return (Criteria) this;
        }

        public Criteria andEncNoTypeNotLike(String value) {
            addCriterion("ENC_NO_TYPE not like", value, "encNoType");
            return (Criteria) this;
        }

        public Criteria andEncNoTypeIn(List<String> values) {
            addCriterion("ENC_NO_TYPE in", values, "encNoType");
            return (Criteria) this;
        }

        public Criteria andEncNoTypeNotIn(List<String> values) {
            addCriterion("ENC_NO_TYPE not in", values, "encNoType");
            return (Criteria) this;
        }

        public Criteria andEncNoTypeBetween(String value1, String value2) {
            addCriterion("ENC_NO_TYPE between", value1, value2, "encNoType");
            return (Criteria) this;
        }

        public Criteria andEncNoTypeNotBetween(String value1, String value2) {
            addCriterion("ENC_NO_TYPE not between", value1, value2, "encNoType");
            return (Criteria) this;
        }

        public Criteria andEncNoIsNull() {
            addCriterion("ENC_NO is null");
            return (Criteria) this;
        }

        public Criteria andEncNoIsNotNull() {
            addCriterion("ENC_NO is not null");
            return (Criteria) this;
        }

        public Criteria andEncNoEqualTo(String value) {
            addCriterion("ENC_NO =", value, "encNo");
            return (Criteria) this;
        }

        public Criteria andEncNoNotEqualTo(String value) {
            addCriterion("ENC_NO <>", value, "encNo");
            return (Criteria) this;
        }

        public Criteria andEncNoGreaterThan(String value) {
            addCriterion("ENC_NO >", value, "encNo");
            return (Criteria) this;
        }

        public Criteria andEncNoGreaterThanOrEqualTo(String value) {
            addCriterion("ENC_NO >=", value, "encNo");
            return (Criteria) this;
        }

        public Criteria andEncNoLessThan(String value) {
            addCriterion("ENC_NO <", value, "encNo");
            return (Criteria) this;
        }

        public Criteria andEncNoLessThanOrEqualTo(String value) {
            addCriterion("ENC_NO <=", value, "encNo");
            return (Criteria) this;
        }

        public Criteria andEncNoLike(String value) {
            addCriterion("ENC_NO like", value, "encNo");
            return (Criteria) this;
        }

        public Criteria andEncNoNotLike(String value) {
            addCriterion("ENC_NO not like", value, "encNo");
            return (Criteria) this;
        }

        public Criteria andEncNoIn(List<String> values) {
            addCriterion("ENC_NO in", values, "encNo");
            return (Criteria) this;
        }

        public Criteria andEncNoNotIn(List<String> values) {
            addCriterion("ENC_NO not in", values, "encNo");
            return (Criteria) this;
        }

        public Criteria andEncNoBetween(String value1, String value2) {
            addCriterion("ENC_NO between", value1, value2, "encNo");
            return (Criteria) this;
        }

        public Criteria andEncNoNotBetween(String value1, String value2) {
            addCriterion("ENC_NO not between", value1, value2, "encNo");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("START_TIME =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("START_TIME <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("START_TIME >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("START_TIME >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("START_TIME <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("START_TIME <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("START_TIME in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("START_TIME not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("START_TIME between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("START_TIME not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("END_TIME =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("END_TIME <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("END_TIME >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("END_TIME >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("END_TIME <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("END_TIME <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("END_TIME in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("END_TIME not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("END_TIME between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("END_TIME not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andLosIsNull() {
            addCriterion("LOS is null");
            return (Criteria) this;
        }

        public Criteria andLosIsNotNull() {
            addCriterion("LOS is not null");
            return (Criteria) this;
        }

        public Criteria andLosEqualTo(String value) {
            addCriterion("LOS =", value, "los");
            return (Criteria) this;
        }

        public Criteria andLosNotEqualTo(String value) {
            addCriterion("LOS <>", value, "los");
            return (Criteria) this;
        }

        public Criteria andLosGreaterThan(String value) {
            addCriterion("LOS >", value, "los");
            return (Criteria) this;
        }

        public Criteria andLosGreaterThanOrEqualTo(String value) {
            addCriterion("LOS >=", value, "los");
            return (Criteria) this;
        }

        public Criteria andLosLessThan(String value) {
            addCriterion("LOS <", value, "los");
            return (Criteria) this;
        }

        public Criteria andLosLessThanOrEqualTo(String value) {
            addCriterion("LOS <=", value, "los");
            return (Criteria) this;
        }

        public Criteria andLosLike(String value) {
            addCriterion("LOS like", value, "los");
            return (Criteria) this;
        }

        public Criteria andLosNotLike(String value) {
            addCriterion("LOS not like", value, "los");
            return (Criteria) this;
        }

        public Criteria andLosIn(List<String> values) {
            addCriterion("LOS in", values, "los");
            return (Criteria) this;
        }

        public Criteria andLosNotIn(List<String> values) {
            addCriterion("LOS not in", values, "los");
            return (Criteria) this;
        }

        public Criteria andLosBetween(String value1, String value2) {
            addCriterion("LOS between", value1, value2, "los");
            return (Criteria) this;
        }

        public Criteria andLosNotBetween(String value1, String value2) {
            addCriterion("LOS not between", value1, value2, "los");
            return (Criteria) this;
        }

        public Criteria andAdmitDeptNameIsNull() {
            addCriterion("ADMIT_DEPT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andAdmitDeptNameIsNotNull() {
            addCriterion("ADMIT_DEPT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andAdmitDeptNameEqualTo(String value) {
            addCriterion("ADMIT_DEPT_NAME =", value, "admitDeptName");
            return (Criteria) this;
        }

        public Criteria andAdmitDeptNameNotEqualTo(String value) {
            addCriterion("ADMIT_DEPT_NAME <>", value, "admitDeptName");
            return (Criteria) this;
        }

        public Criteria andAdmitDeptNameGreaterThan(String value) {
            addCriterion("ADMIT_DEPT_NAME >", value, "admitDeptName");
            return (Criteria) this;
        }

        public Criteria andAdmitDeptNameGreaterThanOrEqualTo(String value) {
            addCriterion("ADMIT_DEPT_NAME >=", value, "admitDeptName");
            return (Criteria) this;
        }

        public Criteria andAdmitDeptNameLessThan(String value) {
            addCriterion("ADMIT_DEPT_NAME <", value, "admitDeptName");
            return (Criteria) this;
        }

        public Criteria andAdmitDeptNameLessThanOrEqualTo(String value) {
            addCriterion("ADMIT_DEPT_NAME <=", value, "admitDeptName");
            return (Criteria) this;
        }

        public Criteria andAdmitDeptNameLike(String value) {
            addCriterion("ADMIT_DEPT_NAME like", value, "admitDeptName");
            return (Criteria) this;
        }

        public Criteria andAdmitDeptNameNotLike(String value) {
            addCriterion("ADMIT_DEPT_NAME not like", value, "admitDeptName");
            return (Criteria) this;
        }

        public Criteria andAdmitDeptNameIn(List<String> values) {
            addCriterion("ADMIT_DEPT_NAME in", values, "admitDeptName");
            return (Criteria) this;
        }

        public Criteria andAdmitDeptNameNotIn(List<String> values) {
            addCriterion("ADMIT_DEPT_NAME not in", values, "admitDeptName");
            return (Criteria) this;
        }

        public Criteria andAdmitDeptNameBetween(String value1, String value2) {
            addCriterion("ADMIT_DEPT_NAME between", value1, value2, "admitDeptName");
            return (Criteria) this;
        }

        public Criteria andAdmitDeptNameNotBetween(String value1, String value2) {
            addCriterion("ADMIT_DEPT_NAME not between", value1, value2, "admitDeptName");
            return (Criteria) this;
        }

        public Criteria andDisDeptNameIsNull() {
            addCriterion("DIS_DEPT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDisDeptNameIsNotNull() {
            addCriterion("DIS_DEPT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDisDeptNameEqualTo(String value) {
            addCriterion("DIS_DEPT_NAME =", value, "disDeptName");
            return (Criteria) this;
        }

        public Criteria andDisDeptNameNotEqualTo(String value) {
            addCriterion("DIS_DEPT_NAME <>", value, "disDeptName");
            return (Criteria) this;
        }

        public Criteria andDisDeptNameGreaterThan(String value) {
            addCriterion("DIS_DEPT_NAME >", value, "disDeptName");
            return (Criteria) this;
        }

        public Criteria andDisDeptNameGreaterThanOrEqualTo(String value) {
            addCriterion("DIS_DEPT_NAME >=", value, "disDeptName");
            return (Criteria) this;
        }

        public Criteria andDisDeptNameLessThan(String value) {
            addCriterion("DIS_DEPT_NAME <", value, "disDeptName");
            return (Criteria) this;
        }

        public Criteria andDisDeptNameLessThanOrEqualTo(String value) {
            addCriterion("DIS_DEPT_NAME <=", value, "disDeptName");
            return (Criteria) this;
        }

        public Criteria andDisDeptNameLike(String value) {
            addCriterion("DIS_DEPT_NAME like", value, "disDeptName");
            return (Criteria) this;
        }

        public Criteria andDisDeptNameNotLike(String value) {
            addCriterion("DIS_DEPT_NAME not like", value, "disDeptName");
            return (Criteria) this;
        }

        public Criteria andDisDeptNameIn(List<String> values) {
            addCriterion("DIS_DEPT_NAME in", values, "disDeptName");
            return (Criteria) this;
        }

        public Criteria andDisDeptNameNotIn(List<String> values) {
            addCriterion("DIS_DEPT_NAME not in", values, "disDeptName");
            return (Criteria) this;
        }

        public Criteria andDisDeptNameBetween(String value1, String value2) {
            addCriterion("DIS_DEPT_NAME between", value1, value2, "disDeptName");
            return (Criteria) this;
        }

        public Criteria andDisDeptNameNotBetween(String value1, String value2) {
            addCriterion("DIS_DEPT_NAME not between", value1, value2, "disDeptName");
            return (Criteria) this;
        }

        public Criteria andDisTypeIsNull() {
            addCriterion("DIS_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andDisTypeIsNotNull() {
            addCriterion("DIS_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDisTypeEqualTo(String value) {
            addCriterion("DIS_TYPE =", value, "disType");
            return (Criteria) this;
        }

        public Criteria andDisTypeNotEqualTo(String value) {
            addCriterion("DIS_TYPE <>", value, "disType");
            return (Criteria) this;
        }

        public Criteria andDisTypeGreaterThan(String value) {
            addCriterion("DIS_TYPE >", value, "disType");
            return (Criteria) this;
        }

        public Criteria andDisTypeGreaterThanOrEqualTo(String value) {
            addCriterion("DIS_TYPE >=", value, "disType");
            return (Criteria) this;
        }

        public Criteria andDisTypeLessThan(String value) {
            addCriterion("DIS_TYPE <", value, "disType");
            return (Criteria) this;
        }

        public Criteria andDisTypeLessThanOrEqualTo(String value) {
            addCriterion("DIS_TYPE <=", value, "disType");
            return (Criteria) this;
        }

        public Criteria andDisTypeLike(String value) {
            addCriterion("DIS_TYPE like", value, "disType");
            return (Criteria) this;
        }

        public Criteria andDisTypeNotLike(String value) {
            addCriterion("DIS_TYPE not like", value, "disType");
            return (Criteria) this;
        }

        public Criteria andDisTypeIn(List<String> values) {
            addCriterion("DIS_TYPE in", values, "disType");
            return (Criteria) this;
        }

        public Criteria andDisTypeNotIn(List<String> values) {
            addCriterion("DIS_TYPE not in", values, "disType");
            return (Criteria) this;
        }

        public Criteria andDisTypeBetween(String value1, String value2) {
            addCriterion("DIS_TYPE between", value1, value2, "disType");
            return (Criteria) this;
        }

        public Criteria andDisTypeNotBetween(String value1, String value2) {
            addCriterion("DIS_TYPE not between", value1, value2, "disType");
            return (Criteria) this;
        }

        public Criteria andParticipantIdIsNull() {
            addCriterion("PARTICIPANT_ID is null");
            return (Criteria) this;
        }

        public Criteria andParticipantIdIsNotNull() {
            addCriterion("PARTICIPANT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andParticipantIdEqualTo(Long value) {
            addCriterion("PARTICIPANT_ID =", value, "participantId");
            return (Criteria) this;
        }

        public Criteria andParticipantIdNotEqualTo(Long value) {
            addCriterion("PARTICIPANT_ID <>", value, "participantId");
            return (Criteria) this;
        }

        public Criteria andParticipantIdGreaterThan(Long value) {
            addCriterion("PARTICIPANT_ID >", value, "participantId");
            return (Criteria) this;
        }

        public Criteria andParticipantIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PARTICIPANT_ID >=", value, "participantId");
            return (Criteria) this;
        }

        public Criteria andParticipantIdLessThan(Long value) {
            addCriterion("PARTICIPANT_ID <", value, "participantId");
            return (Criteria) this;
        }

        public Criteria andParticipantIdLessThanOrEqualTo(Long value) {
            addCriterion("PARTICIPANT_ID <=", value, "participantId");
            return (Criteria) this;
        }

        public Criteria andParticipantIdIn(List<Long> values) {
            addCriterion("PARTICIPANT_ID in", values, "participantId");
            return (Criteria) this;
        }

        public Criteria andParticipantIdNotIn(List<Long> values) {
            addCriterion("PARTICIPANT_ID not in", values, "participantId");
            return (Criteria) this;
        }

        public Criteria andParticipantIdBetween(Long value1, Long value2) {
            addCriterion("PARTICIPANT_ID between", value1, value2, "participantId");
            return (Criteria) this;
        }

        public Criteria andParticipantIdNotBetween(Long value1, Long value2) {
            addCriterion("PARTICIPANT_ID not between", value1, value2, "participantId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated do_not_delete_during_merge Wed Nov 28 13:40:20 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LANGCHAO_XT.ENCOUNTER
     *
     * @mbg.generated Wed Nov 28 13:40:20 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}